export const CART_ACTION_TYPES = {
    UPDATE_CART_ITEMS: 'cart/UPDATE_CART_ITEMS',
    SET_CART_DROPDOWN_IS_VISIBLE: 'cart/ SET_CART_DROPDOWN_IS_VISIBLE',
    ADD_ITEM_TO_CART: 'cart/ADD_ITEM_TO_CART',
    REMOVE_ITEM_FROM_CART: 'cart/REMOVE_ITEM_FROM_CART',
    CLEAR_ITEM_FROM_CART: 'cart/CLEAR_ITEM_FROM_CART',

}