export const USER_ACTION_TYPES = {
    SET_CURRENT_USER: 'user/SET_CURRENT_USER',
    CHECK_USER_SESSION: 'user/CHECK_USER_SESSION',
    SIGN_IN_WITH_GOOGLE_START: 'user/SIGN_IN_WITH_GOOGLE_START',
    SIGN_IN_WITH_EMAIL_AND_PASSWORD_START: 'user/SIGN_IN_WITH_EMAIL_AND_PASSWORD_START',
    SIGN_IN_SUCCESS: 'user/SIGN_IN_SUCCESS',
    SIGN_IN_FAILED: 'user/SIGN_IN_FAILED',
    SIGN_UP_START: 'user/SIGN_UP_START',
    SIGN_UP_SUCCESS: 'user/SIGN_UP_SUCCESS',
    SIGN_UP_FAILED: 'user/SIGN_UP_FAILED',
    SIGN_OUT_USER_START: 'user/SIGN_OUT_USER_START',
    SIGN_OUT_USER_SUCCESS: 'user/SIGN_OUT_USER_SUCCESS',
    SIGN_OUT_USER_FAILED: 'user/SIGN_OUT_USER_FAILED'
}